runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  JIRA_USERNAME: ''
  JIRA_SERVER_URL: ''

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto

instance_class: F1
